[book]
title = "op-boot documentation"
description = "A guide to using op-boot"
authors = ["refcell"]
language = "en"

[rust]
edition = "2018"

[output.html]
mathjax-support = true
site-url = "/mdBook/"
git-repository-url = "https://github.com/anton-rs/op-boot/tree/main/docs"
edit-url-template = "https://github.com/anton-rs/op-boot/edit/main/docs/{path}"

[output.html.playground]
editable = true
line-numbers = true

[output.html.code.hidelines]
python = "~"

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2

[output.html.redirect]
"/format/config.html" = "configuration/index.html"
