all: exec-reth exec-node

exec-node:
	@echo "Executing the op-node..."
	@./op-node.sh
	@echo "Done."
.PHONY: exec-node

exec-reth:
	@echo "Executing reth..."
	@./op-reth.sh
	@echo "Done."
.PHONY: exec-reth

